### ISSUE TITLE
Incorrect levemete for "To the Teeth"

### ISSUE THREAD

**Issue by Hiroa** [Haselnussbomber/LeveHelper#10]
Hi and thanks for this great tool.
The levemete of [To the Teeth](https://ffxiv.consolegameswiki.com/wiki/To_the_Teeth) is incorrect (at least in french)
It should be Keltraeng instead of Kikiri.
![image](https://github.com/Haselnussbomber/LeveHelper/assets/3938368/66e45c43-b1cf-46e8-b613-e11dbc50811c)

**Comment by Haselnussbomber** [comment]
Hey,

you're almost correct. It's not To the Teeth, it's Blood in the Water that's wrong.

Seems to be an issue on the Gamer Escape's wiki, because there are [two leves](https://ffxiv.gamerescape.com/wiki/Blood_in_the_Water) that are called Blood in the Water, one for level 20 from Kikiri, and one for level 68 issued by Keltraeng.

I'll update it soon. 🙂

**Comment by Haselnussbomber** [comment]
Fixed in [v2.1.3](https://github.com/Haselnussbomber/LeveHelper/releases/tag/v2.1.3). 🙂
